#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#构造一个1,3,5,7,...,99的列表
L=[]
n=1
while n < 99 :
    L.append(n)
    n=n+2
print(L)

#   高级函数特性
#   切片
L = ['Michael', 'Sarah', 'Tracy', 'Bob', 'Jack']
print(L[0:3])      #从索引开始取，直到索引3为主，即0,1,2
print(L[:3])        #最重要的操作
print(L[1:3])
print(L[-4:-2])     #倒数是从-1开始，倒数是-2: 冒号在后面

L = list(range(100))
L=[0, 1, 2, 3, ..., 99]
print(L[:10])
print(L[-10:])

'ABCDEFG'[::2]      #隔两个切片
